### ISSUE TITLE
auro-menu: sub-menu

### ISSUE THREAD

**Issue by ftaylor-alaska** [AlaskaAirlines/auro-menu#10]
I would like to have the option to have sub-menu options so that I can organize options by a category.

## Describe the solution you'd like
I would like to be able to nest a menu within a menu

## Alternatives
Add a style to an option which indents it

## Use case: 
The city-list has "pseudo-cities" which is a grouping of near by airports, for example: 
- BA3 (Bay area) has SFO, OAK, SJC
- LA5 (Los Angeles) BUR. LGB, LAX, ONT, SNA

We would like to display these cities grouped together!

**Comment by blackfalcon** [comment]
@ftaylor-alaska is there designer support on this? Prior to any update, we should have a Figma link to discuss.
