### ISSUE TITLE
Should `active` state follow mouseover events?

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-menu#102]
## Describe the bug

Need to investigate if the `active` state for menu options (which applies the light gray background) should also follow `mouseover` events.

The current scenario is that we move the `active` state with the arrow keys only. Focus has the same color pattern but is separate. This results in the possibility of having two menuoptions that both have the light gray background. 

Given the following menu:

Option A
Option B - selected
Option C
Option D - active
Option E

Current implementation is that if you hover the mouse over option A, both Option A and D will have the light gray background. If, while still hovering over Option A, you hit the down arrow key the active state will move to Option E and both A and E will have the light gray background.

The proposal here is that the mouseover event would also move the `active` state just as a the arrow keys do. So given the menu example above, hovering over Option A would remove active from D and place it on A. The next ArrowDown key event would then move active to Option B.

**Comment by leeejune** [comment]
@jason-capsule42 After doing some auditing, the best practice seems to be differentiating the active state and hover state. Therefore, it would be better that the mouseover event would also move the `active` state just as a the arrow keys do.

selected: checkmark, blue color
active/hover: grey color
