### ISSUE TITLE
auro-menu: optionSelected event not dispatched

### ISSUE THREAD

**Issue by ftaylor-alaska** [AlaskaAirlines/auro-menu#11]
## Bug
The `optionSelected` event is never attached to `auro-menuy-option`s that are dynamically created. When there is a static number of `auro-menu-option`s then this event is emitted on click as expected. 

## To Reproduce
1. Create an array of options
2. Map them to `auro-menu-option` 
3. Programmatically add/remove elements from the array
4. The `auro-menu-option`s will not dispatch the `optionSelected` event

## Expected behavior
`optionSelected` event is emitted when an `auro-menu-option` is clicked, even if it was created after the initial lifecycle of the component. We might need to change when the event is created from firstUpdated to update or something similar. 

## Browser Information
 - OS: [W10]
 - Browser [Chromium]
 - auro-menu Version [1.1.0]

**Comment by geoffrich** [comment]
You might need to use the [slotchange event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event) to react to elements being added to the slot. See https://github.com/AlaskaAirlines/auro-accordion/pull/21 for an example.
