### ISSUE TITLE
JS error on hover if auro-menu has <hr />

### ISSUE THREAD

**Issue by bdahl1** [AlaskaAirlines/auro-menu#117]
## Describe the bug

There's a JS issue when you hover over menu options when there's an `<hr /`> tag.

## To Reproduce

1. Go to the [auro-menu page](https://auro.alaskaair.com/components/auro/menu#gsc.tab=0)
1. Open the console
1. Start mousing over options in the Options with horizontal separator version
1. Check the console

## Expected behavior

No errors. Instead we see this:

```
auro-menu__bundled.js:166 Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at re.updateActiveOption (auro-menu__bundled.js:166:18357)
```

In my Angular project I see something similar, so I think this is a general problem:

```
zone.js:182 Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
at HTMLElement.updateActiveOption (auro-menu.js:251:28)
at ZoneDelegate.invokeTask (zone.js:406:31)
at Zone.runTask (zone.js:178:47)
at ZoneTask.invokeTask [as invoke] (zone.js:487:34)
at invokeTask (zone.js:1600:14)
at HTMLElement.globalZoneAwareCallback (zone.js:1626:17)
```

## Desktop (please complete the following information):
 - OS: Windows
 - Browser Chrome
 - Version 100.0.4896.60 (Official Build) (64-bit)

**Comment by blackfalcon** [comment]
@jason-capsule42 thinking this has to do with the latest updates to the hover/arrow accessibility model we are supporting.
