### ISSUE TITLE
Refactor handling of index selection via click event

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-menu#123]
The existing `mousedown` event that calls `clickOption`, and the `clickOption` method itself need to be removed. The functionality is already handled by hover.

The `mousedown` event that calls `makeSelection` may need to be changed to a `click` event. 

However, this requires more thought. The original reason for it being `mousedown` was so that in `auro-select` and `auro-combobox` the user click see the selection happen on `mousedown` but not have the dropdown bib hide until the click event was complete.

It may be enough to change this to click and have auro-select and auro-combox modify their handling of auro-dropdown such that instead hiding the bib on selection the bib is hidden on any auro-menu event of `mouseup`.

**Comment by blackfalcon** [comment]
> However, this requires more thought. The original reason for it being `mousedown` was so that in `auro-select` and `auro-combobox` the user click see the selection happen on `mousedown` but not have the dropdown bib hide until the click event was complete.

The difference is when we were building menu as a standalone element, the `click` event felt weird. Within the context of a dropdown, the `click` is appropriate. E.g. you never see the click, when the selection happens, the dropdown closes.

**Comment by jason-capsule42** [comment]
This issue is now outdated due to more recent changes.
