### ISSUE TITLE
Add missing tests

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-menu#127]
## Describe the bug

Several functional errors need automated testing written

- [ ] `matchWord` functionality
- [ ] keyboard menu navigation
- [ ] menuoption mouseover

Tests need to be written so that all areas of functionality are covered.

**Comment by blackfalcon** [comment]
Code coverage is at [92%](https://github.com/AlaskaAirlines/auro-menu/actions/runs/3115015080/jobs/5051485510#step:5:92).

**Comment by fajar-apri-alaska** [comment]
If I may, I've worked on the rest of the missing test script.

<img width="1440" alt="image" src="https://github.com/AlaskaAirlines/auro-menu/assets/124668226/cb1ae3b3-b90d-45bb-a562-80f309c0a496">

**Comment by blackfalcon** [comment]
@fajar-apri-alaska please fork the repo and present a PR. Thanks!
