### ISSUE TITLE
Text entry filter not working

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#132]
## Describe the bug

Following the directions in the demo does not produce a result. 

## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/menu#gsc.tab=0:~:text=Using%20matchWord%20to%20highlight%20displayValue%20string%20parts
1. Type any value into the input
1. See issue

## Expected behavior

Menu should filter on text entry. 

## Screenshots

<img width="637" alt="Screen Shot 2022-07-14 at 1 14 00 PM" src="https://user-images.githubusercontent.com/181089/179075459-29a318ff-b940-42c3-83df-b48cc75f3207.png">

**Comment by jason-capsule42** [comment]
Duplicate issue for https://github.com/AlaskaAirlines/auro-menu/issues/133

Fixing #133 will fix this.
