### ISSUE TITLE
JS examples need to be updated to use the new examples.js system to ensure the JS loads correctly

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#133]
## To Reproduce

1. Go to https://auro.alaskaair.com/components/auro/menu#gsc.tab=0:~:text=Menuoption%20with%20custom%20event
1. Click on 'new address' in menu
1. See error

## Expected behavior

Alert should appear. 

## Screenshots

<img width="660" alt="Screen Shot 2022-07-14 at 1 14 10 PM" src="https://user-images.githubusercontent.com/181089/179075753-482bbf79-a61e-4a20-9370-0e323ad32e1d.png">

**Comment by jason-capsule42** [comment]
This is no longer relevant due to more recent changes.
