### ISSUE TITLE
apiExamples.md  file is not generated

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-menu#148]
## Describe the bug

No examples for any public attributes or functions in the API.

## To Reproduce

1. Go to [menu](https://auro.alaskaair.com/components/auro/menu).
2. Click on API tab.
3. See that there are no examples.

## Expected behavior

API examples present.

**Comment by blackfalcon** [comment]
The current automated task of creating API examples is not persistent between all component repos and is a custom add to the repo. 

It's preferred that this feature be baked into the generator and added to the repo when the repo is upgraded.
