### ISSUE TITLE
Arrow key navigation is not skipping hidden menu items

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-menu#156]
## Describe the bug

When using the arrow keys (up/down) to navigate the menu (e.g. in combobox), hidden items are not being skipped. This results in combobox making selections that it should not.

## To Reproduce

1. Go to the airport example on the combobox demo
1. Type the letter a
1. use the arrow keys to navigate up and down the menu
1. See error

## Expected behavior

You should not see skips in the navigation where it looks like you no longer have an "active" menu option.

**Comment by blackfalcon** [comment]
**Confirmed**. Type on `mke` into the airports and hit the arrow key down `5` times and hit enter. You should see `yakima air terminal`.
