### ISSUE TITLE
Should be able to select scroll bar to scroll through options

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-menu#159]
## Describe the bug

When using auro-select with a fixed height and a scroll bar is visible, the scroll bar isn't clickable.  It appears that you can click on the menu options below the scroll bar.

## To Reproduce

The flight search team implemented the work around Geoff suggested for the currency converter.

Scroll down to the bottom of the page and click on the currency converter in the fine print.
1. Click on [flight search](https://www.alaskaair.com/search/results?A=1&O=sea&D=las&OD=2023-08-25&OT=Anytime&DD=2023-08-25&DT=Anytime&UPG=none)
1. Scroll down to the bottom of the page and click on the currency converter in the fine print.
1. See error

## Expected behavior

A user can click on the scroll bar without closing the bib.

## Desktop (please complete the following information):

 - OS: Windows & Mac appear to both have slightly different experiences

**Comment by braven112** [comment]
See this issue for background 
- https://github.com/AlaskaAirlines/auro-select/issues/115

**Comment by jordanjones243** [comment]
This ticket will be fixed by this, once completed an update and PR will be released to implement the change:
- https://github.com/AlaskaAirlines/auro-menu/issues/159
