### ISSUE TITLE
Uncheck disabled option

### ISSUE THREAD

**Issue by jesussilverioea** [AlaskaAirlines/auro-menu#174]
## Describe the bug

When a disabled option that is marked as "checked" should not be able to be uncheck once we click on it.

## To Reproduce

on the [Auro menu site](https://auro.alaskaair.com/components/auro/menu) you can add the attribute on one of the ```disabled``` <auro-menuoption> and once you click on it it becomes unchecked. 

https://user-images.githubusercontent.com/108018885/234120696-fdcbee7b-c624-4c4f-ba96-b06bd43db6d7.mov

## Expected behavior

once an option is marked as checked and disabled should not become uncheck by clicking on itself. It should marked itself as uncheck if another element in the auro menu is clicked.

## Additional context

We also do not have the capability to marked the entire menu as unchecked as in other components e.g auro-radio-group

**Comment by blackfalcon** [comment]
I can get on board that this is something to be supported when a menu item is pre-selected on paint and then the menu item is disabled. A user should not be able to uncheck that.

**Comment by fajar-apri-alaska** [comment]
Hi Team.
This can be solved with below solution  in `handleMouseDown` function like so:
<img width="642" alt="image" src="https://github.com/AlaskaAirlines/auro-menu/assets/124668226/813c38c2-411a-42b1-a7aa-4ba006231e94">

Actually, I'm not sure where to put the checking condition. Maybe just combine it like:
<img width="642" alt="image" src="https://github.com/AlaskaAirlines/auro-menu/assets/124668226/4050495d-e7c6-4bad-bd21-4570df4ba36a">

**Comment by blackfalcon** [comment]
Thanks @fajar-apri-alaska we will look at this and see if we can get this issue prioritized.

**Comment by braven112** [comment]
Notes from refinement:
Double check that we are blocking keyboard as well as mouse for this bug as well.

**Comment by fajar-apri-alaska** [comment]
> Notes from refinement: Double check that we are blocking keyboard as well as mouse for this bug as well.

You're right @braven112, I tried to force the focus to the disabled option with mouse click first, and press Enter, it did happened again.
So instead of previous solution, in the makeSelection function we check if the target has `disabled` attribute, then it will do nothing.

<img width="830" alt="image" src="https://github.com/AlaskaAirlines/auro-menu/assets/124668226/4e81d194-2059-4552-9e02-4b99a0a79108">

Please advise.
