### ISSUE TITLE
Ability to disable auro-menu

### ISSUE THREAD

**Issue by jesussilverioea** [AlaskaAirlines/auro-menu#175]
## Is your feature request related to a problem? Please describe.

We should have the ability to disable the entire menu. Similarly to [auro-radio-group](https://auro.alaskaair.com/components/auro/radio/api) that has the ability do disable the clickability of the elements inside.

![image](https://user-images.githubusercontent.com/108018885/234128519-bee0e9ab-29e4-4b2e-a410-dac8fe69079a.png)

## Describe the solution you'd like

I would like to have the ``disable`` attribute that we could send to the auro-menu to disable the entire elements inside the menu. 

## Describe alternatives you've considered

I have tried to disable the auro-menuoptions but this would disable 1 element in the menu not the entire functionality of the menu. At the moment when an element is checked and then clicked on it it would unchecked it even if it is disable.

I open an issue to address the uncheck when disable:
https://github.com/AlaskaAirlines/auro-menu/issues/174

**Comment by blackfalcon** [comment]
@jesussilverioea is this a desired feature or something that is functionality required for your app? Are you blocked by this?
