### ISSUE TITLE
auro-menu: mobile breakpoint full screen takeover

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-menu#183]
## Is your feature request related to a problem? Please describe.

In moving towards a filtering 'super-menu' we would like auro-menu to have the ability to do a full screen takeover when clicked into at the mobile breakpoint.

![image](https://github.com/AlaskaAirlines/auro-menu/assets/34354487/575df781-61f1-4c6f-b3b9-6276659437bb)

## Describe the solution you'd like

Ability for a full screen supermenu at mobile breakpoint, just like is implemented when you currently click into the auro-datepicker on a mobile device.

![image](https://github.com/AlaskaAirlines/auro-menu/assets/34354487/a35a9922-636e-4717-9bf2-049fa86c1f1c)

**Comment by blackfalcon** [comment]
Thanks @erikalanghauser we will get this into review ASAP. This particular type of issue is coming up more and more.

**Comment by Patrick-Daly-AA** [comment]
We'll be handling this with auro-dropdown #183
