### ISSUE TITLE
auro-menu: multiselect

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-menu#199]
### Is your feature request related to a problem? Please describe.

As a business I want to give users the ability to select multiple options from menu items
So that users can select multiple options in the UI.

Blueprint:
https://www.figma.com/file/yMshXAiKZrkLDdiX8N4GKQ/Multi-Select-Combo-Box?type=design&node-id=114-3745&mode=design&t=R007FIBn8d6HGOOY-11

### Describe the solution you'd like

A menu with checkboxes so users can select as many as they want.

### Exit criteria

1. Auro-menu feature matches the blueprint.
2. Create refinement meeting team on next step to align on implementation of next step.
3. As an outcome of the refiement a new issue is created to implement this as either `<auro-multiselect>` or `<auro-combobox multiselect>`
4. When Menu is Multiselect, value is an Array containing all selected menu options.

**Comment by chrisfalaska** [comment]
This work has been moved to `auro-formkit` and will be completed in https://github.com/AlaskaAirlines/auro-formkit/issues/123
