### ISSUE TITLE
Review use of dividers 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#20]
# General Support Request

https://github.com/AlaskaAirlines/auro-menu/pull/19#discussion_r694365772

## Support request

Review current solution and evaluate for an alternate way to address the UI issue. 

## Possible Solution

Thinking a CSS solution is potentially optimal.

**Comment by ftaylor-alaska** [comment]
Checking in on the progress for this, is it something that can be temporarily mitigated using PR #19 and later be cleaned up in a another commit?

**Comment by blackfalcon** [comment]
This issue is too old. The area of concern has been addressed.
