### ISSUE TITLE
Remove code for `hidden` and `static` attributes for `auro-menuoption`

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/auro-menu#206]
### General Support Request

When looking through the code, there are multiple references to `hidden` and `static` attributes in the JS and style files, but there is no code to support these attributes in `auro-menuoption`.

### Possible Solution

Remove all references to `hidden` and `static` attributes

### Exit criteria

Code for `hidden` and `static` attributes is removed.

**Comment by Patrick-Daly-AA** [comment]
Working as intended.  These attributes are used by Combobox.
