### ISSUE TITLE
v2.0-rc

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-menu#22]
## NEXT MAJOR release 

The following items are to be included with the next MAJOR release of the auro-menu transitioning it from `auroLabs` to `auro` all PRs are to be from the feature branch to `v2.0-rc` branch.

Please refer to [this document](https://www.figma.com/file/HKtbt2KXrM1pnayGtYt9KM/Flight-Search-Build-Strategy?node-id=0%3A1) for background on how this component will be architected.

- [x] #24
- [ ] Leave code as is when upgrading the generator

### Do this in the context of auro-dropdownmenu
- [x] #7

### Styles
>- [x] Blueprint
>- [x] #30
>- [x] #20
>- [x] #6
>- [ ] Text overflow for menu items is not working.

>- [ ] Review the A11Y needs. 

### Publish
>- [x] #23 
>- [ ] Add to the doc site

**Comment by blackfalcon** [comment]
v2.0 has been released and triggered via this commit https://github.com/AlaskaAirlines/auro-menu/commit/ba8996dfe8f5c7ea668a15b12a1e3579703a4db5

This RC issue is no longer valid, all issues will be moved to a future release.
