### ISSUE TITLE
Publish to Auro Design System

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#23]
# Publish Component

## Specific steps required to publish this component.

All of the steps outlined below must be completed.

### Design & Planning
- [x] Reviewed [AuroLabs documentation](http://auro.alaskaair.com/)
- [x] Reviewed [Auro's Contributing Guidelines](http://auro.alaskaair.com/contributing)
- [x] Reviewed [Auro's CSS conventions](http://auro.alaskaair.com/webcorestylesheets/conventions) and how to apply CSS to custom elements
- [ ] Design team engaged in designing the new component
- [ ] Design work integrated in the Auro Design System UI Kit

### Development
- [x] https://github.com/AlaskaAirlines/auro-menu/issues/52
- [x] #48 
- [x] Component built using the latest version of [WC-Generator](http://auro.alaskaair.com/getting-started/developers/generator/install)
- [x] #54
- [ ] #55 (issue left open, will be addressed with v3.1 release)

### Documentation
- [x] #40 
- [x] Examples and use case info
- [x] Bundled version info
- [x] README doc completed with all relative information
- [x] API documentation created

### Testing
- [Browser compatibility](http://auro.alaskaair.com/support/browsersSupport) - desktop and mobile versions
  - [x] Chrome
  - [x] Firefox
  - [x] Edge (79 +)
  - [x] Safari
- [Accessibility](http://auro.alaskaair.com/a11y-statement) - One or more of the following
  - [x] Axe / Google Lighthouse (baseline standard)
  - [ ] Screenreader (determine usability of experience via screenreader)
  - [ ] Keyboard use (a user must be able to navigate to key parts via a keyboard)
  - [ ] Accessibility should be verified against all browsers
- [x] Bundled versions tested

### Review
Up until the review phase ensuring compliance with the above checklist is the responsibility of the component contributor. Once Design & Planning, Development, Documentation and Testing have been completed you will need a final review phase completed, particularly the Auro Design System team. The final review will verify that all requirements above have indeed been achieved.

When the component is ready for a final review with your designer and the Auro Design System team it is the responsibility of the contributor to coordinate the following reviews:

- [x] Review demo with the designer
- [x] Review demo with Auro Team
- [x] All work is reviewed by Auro team

**Comment by blackfalcon** [comment]
This isn't necessarily blocked or waiting on feedback, but more so this will be ongoing for a bit while we evaluate the code and plan appropriate refactoring in preparation for official release.

**Comment by blackfalcon** [comment]
@leeejune can you do a design review of https://alaskaairlines-auro-menu-pr-73.surge.sh/

**Comment by leeejune** [comment]
<img width="1042" alt="Screen Shot 2022-01-21 at 2 30 22 PM" src="https://user-images.githubusercontent.com/55998746/150608712-91ae4dd1-1b4d-47e7-97c3-dc11cbc42599.png">

- Icon color should be "auro-color-icon-primary-on-light"
- There should be 12px padding on the left of the icon
- Divider should be "auro-color-border-divider-on-light"

Question:
![Screen Shot 2022-01-21 at 2 28 35 PM](https://user-images.githubusercontent.com/55998746/150608940-aede452a-a9b8-456f-aac9-ccf8e6826143.png)
Should this pre selected option be in the same blue selected state?

**Comment by blackfalcon** [comment]
@leeejune [demo URL](https://alaskaairlines-auro-menu-pr-73.surge.sh/) updated

**Comment by leeejune** [comment]
@blackfalcon Looks good! Design review done.
