### ISSUE TITLE
Disable a menu item

### ISSUE THREAD

**Issue by steve-nickerson** [AlaskaAirlines/auro-menu#25]
## Is your feature request related to a problem? Please describe.
We have a use case where an item in the dropdown needs disabling. e.g.) Search Preferences in Reissue path for Saver fares. The current legacy implementation handles this and as part of our conversion to using auro components, we need this feature for consistency.

## Describe the solution you'd like
Ability to disable a menu item in the dropdown list. Either by index or by value.

## Describe alternatives you've considered
We currently do not have an alternative nor a workaround using this component for disabling an item.

## Additional context
Cross posting in the aurolabs-dropdownmenu for visibility.

**Comment by blackfalcon** [comment]
We will review this feature request with upcoming sprint refinements.
