### ISSUE TITLE
Create figma blueprint file

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-menu#28]
# General Support Request

The auro-menu requires a blueprint supporting document to be released to Figma.

## Support request

Review the current state of the auro-menu design and create the Figma blueprint document. 

## Possible Solution

Design to review current UI for new design opportunities.

## Exit criteria 

- [x] complete blueprint work ([Link](https://www.figma.com/file/xwDiIDfSz6j9bM4TD3Ni5N/Menu?node-id=322%3A298))
- [ ] signoff from Auro engineering (Dale Sande)

## Next steps 

When this element blueprint is added to the Figma Auro UI Kit, this is intended to be used by the new auro-slider as an example.

- [ ] link new issues(s) from development plan to this design issue
- [ ] create new issue for the official release of the design blueprint (dependency on completed Auro component).

**Comment by leeejune** [comment]
Blueprint completed. Review needed.

**Comment by blackfalcon** [comment]
This text should be white? 

<img width="834" alt="Screen Shot 2021-11-15 at 6 15 39 PM" src="https://user-images.githubusercontent.com/181089/141883521-c1687456-6279-4164-b9fa-c9c8110c3585.png">

I am not sure I understand what is happening here? 

<img width="694" alt="Screen Shot 2021-11-15 at 6 18 00 PM" src="https://user-images.githubusercontent.com/181089/141883755-eeaa725b-796e-4eb8-9e33-08f059447c1d.png">

I am not sure this needs to be illustrated? 

<img width="1081" alt="Screen Shot 2021-11-15 at 6 18 54 PM" src="https://user-images.githubusercontent.com/181089/141883850-7ba95826-1a93-4085-9bf3-c4f34fa6e678.png">

**Comment by jason-capsule42** [comment]
The divider should be shown as a separate element that can be in `auro-menu` rather than just a border on the bottom of a menu-item. 

The `structure` section should be simplified as a reaction to that. There wouldn't be different versions of the menu item based on the presence of the divider.

**Comment by jason-capsule42** [comment]
<img width="1270" alt="Screen Shot 2021-11-16 at 8 48 25 AM" src="https://user-images.githubusercontent.com/23223137/142029191-9f725e43-0b42-4441-8f29-8c7d84d2a945.png">

**Comment by jason-capsule42** [comment]
<img width="496" alt="Screen Shot 2021-11-16 at 8 51 40 AM" src="https://user-images.githubusercontent.com/23223137/142029385-2f00708b-68bd-4eb2-aff4-1690433c29b3.png">

**Comment by jason-capsule42** [comment]
<img width="1025" alt="Screen Shot 2021-11-16 at 8 54 50 AM" src="https://user-images.githubusercontent.com/23223137/142030255-7a17caa3-51a6-487d-bdcf-1136bb47d853.png">

**Comment by jason-capsule42** [comment]
<img width="1165" alt="Screen Shot 2021-11-16 at 8 59 02 AM" src="https://user-images.githubusercontent.com/23223137/142030648-9ac7fffd-bbab-43dd-8422-f790dca24246.png">

**Comment by leeejune** [comment]
@jason-capsule42 All changes made accordingly. The components on the left in the purple border are for the designers and it will be moved.

**Comment by jason-capsule42** [comment]
<img width="629" alt="Screen Shot 2021-11-16 at 9 22 11 AM" src="https://user-images.githubusercontent.com/23223137/142034526-34146166-b87b-4f8a-82ab-bc8d1728eb98.png">

**Comment by jason-capsule42** [comment]
<img width="652" alt="Screen Shot 2021-11-16 at 9 24 03 AM" src="https://user-images.githubusercontent.com/23223137/142034633-b5300fbd-ca42-4209-a854-bf28cff6f1fb.png">

Looks like the label text isn't using the disabled color here like it does in the other locations.

**Comment by leeejune** [comment]
@jason-capsule42 My bad. I made a change in Figma that made all the text color black unintentionally. Changes made!

**Comment by blackfalcon** [comment]
Adding my name to this... need to start paying attention to this one.

**Comment by blackfalcon** [comment]
Reviewing design with the current body of work.

**Comment by leeejune** [comment]
Added no check option.

**Comment by blackfalcon** [comment]
@leeejune please see #56

**Comment by blackfalcon** [comment]
@leeejune what is the definition of a nonselectable menu?

**Comment by leeejune** [comment]
> 

I will do some research and get back to you on this!



> @leeejune what is the definition of a nonselectable menu?

A menu that closes immediately when a user selects an item.

**Comment by blackfalcon** [comment]
@leeejune re: nonselectable menu

That is not really a thing? Take a look at this [HTML example](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select) of a select menu. 

The operation is that when the item is selected, the many closes. But when re-opining the menu, there is a check next to the item that is selected. 

A 'nonselectable menu' implies that nothing can be selected, i.e. disabled?

**Comment by leeejune** [comment]
https://github.com/AlaskaAirlines/auro-menu/issues/33

Ah, I understand now. The 'non-selectable' menu I created was a version for a menu without a checkmark. I named it inaccurately. What would be a better way to name a menu item with no check mark?

This is an example that illustrates what I was imagining: https://mui.com/components/menus/#menulist-composition

Would this work?

EDIT: I will be adding a "selected" state for the non checked version. This should also resolve https://github.com/AlaskaAirlines/auro-menu/issues/56#event-5876050348.

**Comment by leeejune** [comment]
https://www.figma.com/file/xwDiIDfSz6j9bM4TD3Ni5N/Menu?node-id=322%3A891

Changes made:

- changed 'non-selectable' to no checkmark (open to new names)
- added 'selected' state for 'no checkmark selection' menu items

**Comment by blackfalcon** [comment]
@leeejune if you can update the Figma doc to say, "submenu feature is not yet released" then you can go ahead and release this component UI. 

https://github.com/AlaskaAirlines/auro-menu/issues/79

**Comment by leeejune** [comment]
Updated blueprint by moving future features to a separate page (in Future Releases page).

**Comment by blackfalcon** [comment]
@leeejune OMG! ❤️ LOVE! ❤️  Ship 🚢 it!

**Comment by leeejune** [comment]
@blackfalcon Ship sailed! ⚓️

**Comment by blackfalcon** [comment]
@leeejune I feel like this has run its course. If there is nothing more to do in this scope, please close the issue. Any new design reviews I imagine will happen with the UI review we discussed?
