### ISSUE TITLE
Update Figma to support non-checked version

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#33]
# General Support Request

The figma blueprint needs to additionally support a use case where a checkmark is not used. 

## Screenshot 

<img width="444" alt="Screen Shot 2021-12-14 at 2 05 44 PM" src="https://user-images.githubusercontent.com/181089/146086900-5c2bb482-a210-4ea8-897b-9ab5a874d756.png">

**Comment by leeejune** [comment]
https://www.figma.com/file/xwDiIDfSz6j9bM4TD3Ni5N/Menu?node-id=322%3A298

No check option already added in the blueprint!
