### ISSUE TITLE
Refactor: programmatically change the value from parent component after initial render

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-menu#51]
## Is your feature request related to a problem? Please describe.

Currently I can do the following:

```html
<auro-dropdownmenu indexSelectedOption="4">
  <span slot="label">Label</span>
  <span slot="helperText">Helper Text</span>
  <auro-menu slot="menu" checkmark>
    <auro-menu-option slot="listOfOptions" data-value="Stops">Stops</auro-menu-option>
    <auro-menu-option slot="listOfOptions" data-value="Price">Price</auro-menu-option>
    <auro-menu-option slot="listOfOptions" data-value="Duration">Duration</auro-menu-option>
    <auro-menu-option slot="listOfOptions" data-value="Departure">Departure</auro-menu-option>
    <auro-menu-option slot="listOfOptions" data-value="Arrival">Arrival</auro-menu-option>
    <auro-menu-option slot="listOfOptions" data-value="Prefer Alaska">Prefer Alaska</auro-menu-option>
  </auro-menu>
</auro-dropdownmenu>
```

Upon initially rendering the menu it will handle the parent declaration of indexSelectedOption correctly. However, I can't just change that value after it initially renders, nor am I sure that would be the best way to go about it.

## Describe the solution you'd like

I think the best option here is to expose a method like "setMenuSelectedIndex(index)" which will essentially perform the same actions as defined for clicking on the `auro-menu-option` with the same index value.

It may be a better option to use such a method for setting the initial value from the parent element as well rather than the current solution which feels like a hack to me since only the direct parent element is capable of controlling the selected index.

**Comment by blackfalcon** [comment]
This issue is outdated given the revisions in the current release. Please review the issue and update as necessary.

**Comment by blackfalcon** [comment]
Closing issue based on previous comment.
