### ISSUE TITLE
attributeChangedCallback is not doing anything? 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#59]
This code needs to be reviewed. As far as I can tell, I am not sure it is actually working as expected? 

https://github.com/AlaskaAirlines/auro-menu/blob/cd3e9340ba8ba475dc2405e894a2e6a377de4de2/src/auro-menu.js#L171-L185

@BrentLabasan or @ftaylor-alaska can you help me understand the role this has? I can comment out the code and nothing fails?

**Comment by geoffrich** [comment]
As far as I can tell, this is setting tabindex of all options to -1 when the `ishidden` attribute is set, and setting tabindex to 0 when `ishidden` is removed. There's probably a better place to do this besides `attributeChangedCallback`, though. The [Lit docs](https://lit.dev/docs/components/lifecycle/#attributechangedcallback()) say you rarely need to implement this. One of the [update lifecycles](https://lit.dev/docs/components/lifecycle/#reactive-update-cycle) would be better.

**Comment by blackfalcon** [comment]
When I test this in the demo, I am not seeing that happen. That's why I am asking for more background on this. And I agree, this should probably be refactored to a lifecycle event, but not wanting to do that if I don't understand the test case.

**Comment by blackfalcon** [comment]
I removed the `isHidden` attr in this [pr](https://github.com/AlaskaAirlines/auro-menu/pull/58/commits/983cfbbee91b268db1f5da62b2d345a0dfb09640) as I cannot see any evidence of this doing anything. 

It's in a separate commit that I can blow away if this is needed.

**Comment by BrentLabasan** [comment]
Based on what was said in https://github.com/AlaskaAirlines/auro-menu/issues/60 , the code in the code snippet up above can be removed.
