### ISSUE TITLE
hideOptionsContainer

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#60]
This code is being referenced in the [auroLabs version](https://github.com/AlaskaAirlines/aurolabs-dropdownmenu/search?q=hideOptionsContainer), but not the [new repo](https://github.com/AlaskaAirlines/auro-dropdownmenu/search?q=hideOptionsContainer)

I believe that it is intended to trigger an event that when a user tabs to the last item in a menu, upon the next tab event this will close the dropdown. 

https://github.com/AlaskaAirlines/auro-menu/blob/cd3e9340ba8ba475dc2405e894a2e6a377de4de2/src/auro-menu.js#L131-L138

This is to be considered in the accessibility model. 

When looking at a traditional combobox select menu, the accessibility model is that a user will TAB TO the trigger of the dropdown. Then a subsequent tab will move to the next tabable object. It's only an ARROW KEY that will open the menu and allow the user to move between the options. The TAB KEY has no effect. 

So if the intent is to close the menu on the last tab, that should not be supported. It's an unexpected experience. 

With the following code, the scenario is supported that will allow a user to infinitely loop through the options with the arrow keys

https://github.com/AlaskaAirlines/auro-menu/blob/cd3e9340ba8ba475dc2405e894a2e6a377de4de2/src/auro-menu.js#L141-L145

This is non-standard, but I will accept this as an enhancement to be supported.

**Comment by blackfalcon** [comment]
@jason-capsule42 do you have any information about the `hideOptionsContainer` event?

**Comment by jason-capsule42** [comment]
> @jason-capsule42 do you have any information about the `hideOptionsContainer` event?

I don't have anything specific. I assume this was an attempt to handle tabindex but I don't think we need this anymore.

**Comment by blackfalcon** [comment]
The code was actually removed with the previous release and the issue as it is written is no longer valid.
