### ISSUE TITLE
How does this 'inject a checkmark'? 

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#63]
Understand this code and document as needed. 

https://github.com/AlaskaAirlines/auro-menu/blob/cd3e9340ba8ba475dc2405e894a2e6a377de4de2/src/auro-menu.js#L157-L169

**Comment by jason-capsule42** [comment]
Line 163 - dispatchEventOptionSelected will set the checkmark.

**Comment by blackfalcon** [comment]
Refactor addressed with https://github.com/AlaskaAirlines/auro-menu/pull/58/commits/fb864c87c3089081fdbca3f12399079e990cbb02
