### ISSUE TITLE
Refactor event listeners, potential memory leak

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-menu#66]
This code adds event listeners on slot change to each option, but never removes them:

https://github.com/AlaskaAirlines/auro-menu/blob/49195056d881dbab5bb9211c593e32d1e62f3a66/src/auro-menu.js#L154-L164

This can cause a memory leak. I'm also suspicious of it running on every slot change -- what if an element is added to the slot, but nothing is removed? I think it would then add event listeners to slotted elements that already have them.

**Comment by blackfalcon** [comment]
I am not going to say that it's a bug specifically, but you are clearly identifying an area that should be refactored.
