### ISSUE TITLE
indexSelectedOption supported on parent node

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#67]
Got it... I understand what this is doing now. This looks to see of `indexSelectedOption` is on a wrapping undefined parent? E.g. 

```html
  <auro-thing indexSelectedOption="2">
    <auro-menu id="auroMenu2" icon>
      <auro-menu-option data-value="Stops">Stops</auro-menu-option>
      <auro-menu-option disabled data-value="Price">(disabled) Price</auro-menu-option>
      <auro-menu-option data-value="Duration">Duration</auro-menu-option>
      <auro-menu-option data-value="Departure">Departure</auro-menu-option>
      <auro-menu-option data-value="Arrival">Arrival</auro-menu-option>
    </auro-menu>
  </auro-thing>
```

**Question:** Why would we support this? If the API is defined that `indexSelectedOption` is to be on `auro-menu` why would this be needed?

_Originally posted by @blackfalcon in https://github.com/AlaskaAirlines/auro-menu/pull/58#discussion_r787112159_

**Comment by jason-capsule42** [comment]
Turns out this wasn't actually broken and the problem was how auro-menu was imported into auro-dropdownmenu. The fix there
