### ISSUE TITLE
Definition of disabled for design docs

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-menu#68]
# General Support Request

The current design docs illustrate a fully disabled list of selectable elements when a menu is exposed. Current functionality for the menu supports an individual option to be disabled and there is no current use case for a whole menu to be disabled. 

<img width="204" alt="Screen Shot 2022-01-20 at 9 19 34 AM" src="https://user-images.githubusercontent.com/181089/150389227-a7b4fc21-8af1-445e-b250-7d08c751e78b.png">

With the current auro-dropdownmenu if a whole menu were to be disabled, the action to open the menu would be disabled. 

## Support request

Please update the figma doc to illustrate only an option disabled. 

<img width="506" alt="Screen Shot 2022-01-20 at 9 15 40 AM" src="https://user-images.githubusercontent.com/181089/150389301-9c789cb6-d707-4c09-9ac0-7ee3b0bf916a.png">

An option to disable a whole menu can be explored in a later iteration.

**Comment by leeejune** [comment]
This was mostly meant for designers. The design currently supports a single disabled option (last item on the left example of "Default".

Would it be possible to disable every single option to mimic this?

**Comment by blackfalcon** [comment]
Solution: each node can be `disabled` individually, but there is no current or planned functionality to disable a whole menu at this time.
