### ISSUE TITLE
auro-menu: Auro-menu-options should not be focusable when hidden from user

### ISSUE THREAD

**Issue by audreychae97** [AlaskaAirlines/auro-menu#7]
## Describe the bug
Auro-menu-options contain a tabIndex="0" attribute, causing it to be tab-able. This is an accessibility issue because the guest is required to tab through every menu option before being able to move onto the next input element. This also causes the screen reader to read through each option even if the guest didn't expand the dropdown.

After the user tabs through all of the menu-options (not ideal), the next time the guest repeats this tabbing sequence this issue doesn't seem to happen again. They're able to jump to the next input element as expected. 

## To Reproduce
1. Go to an auro drop down that is next to another input element 
2. Start tabbing through the page
3. When the tab hits the drop down and you DON'T select 'enter' to expand the results, hit tab again to move on to the next part of the form 
4. See that the focus/tab does not move on, and visually you don't see the focus for a while until you tab through all of the menu options that aren't expanded

(we would also be happy to show you on our local microsite) 

## Expected behavior
When a guest who is using the keyboard tabs through a page containing an auro-dropdown,
if they choose to NOT expand the drop down and tab past the drop down, they should be able to do so without having to tab through every menu option. 

## Screenshots
User tabs over to the dropdown but doesn't select enter to expand:
![image](https://user-images.githubusercontent.com/17225891/119394878-97e66e00-bc87-11eb-94d5-bf8f481ccb44.png)

User clicks tab again to get to the next input element (the 'To' input field), and is unable to do so until each menu option was tabbed over. 
![image](https://user-images.githubusercontent.com/17225891/119394771-6ff70a80-bc87-11eb-88b3-31f0ad375979.png)

User tabs through all of the hidden menu options and is finally able to get to the next input element:
![image](https://user-images.githubusercontent.com/17225891/119395308-2b1fa380-bc88-11eb-98ec-bd7eb75bee67.png)

## Desktop (please complete the following information):
 - OS: Windows
 - Browser: Chrome 
 - Version 

## Smartphone (please complete the following information):
 - Device: iPhoneX 
 - OS: iOS
 - Browser Chrome 
 - Version

**Comment by jason-capsule42** [comment]
This issue stems from when `auro-menu` is inside a hideable element like the dropdown of `auro-dropdownmenu`.

**Comment by braven112** [comment]
The responsibility of the tabindex will happen in the containing element as an example the dropdownmenu component.
