### ISSUE TITLE
Checkmark vs no checkmark selection

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-menu#87]
## Is your feature request related to a problem? Please describe.

There are mixed opinions about whether the menu should include a checkmark to indication a selection.

## Describe the solution you'd like

Consult UI designers to find best solution to indicate selection. We will be weighing the different options and finding a more effective solution for our brand.

**Comment by blackfalcon** [comment]
Add me back when a review is needed.

**Comment by blackfalcon** [comment]
I came across this from the spectrum picker element. 

<img width="348" alt="Screen Shot 2022-02-17 at 4 53 08 PM" src="https://user-images.githubusercontent.com/181089/154596705-b0d57561-ee91-4b9c-968b-90dabcba0f19.png">

It would be interesting to consider this option for the check mark. This would also make it much simpler to support a use case of checkmark or no checkmark.

**Comment by leeejune** [comment]
After the UI sync, the consensus was that the checkmark should be on the left. If having the checkmark as an option is not possible, having the checkmark would be preferred.

The checkmark should live on the left side due to readability issues with horizontally longer options. The only change that should be made to menu is spacing and hover color. This will be added to issue #88.

What are the engineering limitations @blackfalcon?

**Comment by blackfalcon** [comment]
@leeejune there are no limitations per se. It's more of an issue of complexity. 

I'd like to see the outcome of #88 before making the next set of decisions.

**Comment by leeejune** [comment]
For now, we will just have a checkbox as an indicator for a selection. If there is a demand for no check mark options, we can add it in a future release.

**Comment by blackfalcon** [comment]
Unless I am understanding this wrong, the current decision has no work associated with it. So closing this issue. 

When the time comes that a non-checkmark UI is requested, we will create a new issue for that specific work.

**Comment by braven112** [comment]
Reopening this issue.  We want to have an option to optionally turn on or off the checkbox.    In auro-combobox the checkbox doesn't make sense in most use cases.
