### ISSUE TITLE
Revise UI design for better accessibility and consistency

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-menu#88]
## Is your feature request related to a problem? Please describe.

There are several versions of menu. We should find one design that follows accessibility guidelines and fits our brand DNA.

## Describe the solution you'd like

Revise the blueprint with menu used in the Accounts page.

**Comment by blackfalcon** [comment]
Add me back when a review is needed.

**Comment by leeejune** [comment]
After our conversation, I remembered that I added a hover state token for backgrounds (color states that do not have a separate hover state like auro-color-ui-hover-on-light). auro-color-ui-bkg-hover-on-light has low opacity so it inherits some of the background color the hover state is applied on.

If we change the hover state of menu, we should replace all the hover states in other components that currently use "background-lighter". Changing the hover state just for menu would take away the consistency in other components' hover states. For example, dropdown and secondary button uses background-lighter for their hover states. 

I found examples of hover in Material UI being a similar shade to ours right now. There are no specific accessibility guidelines (contrast ratio) behind hover states. However, I will be darkening the bkg-hover color anyway.

Thoughts? @blackfalcon

**Comment by blackfalcon** [comment]
Let's schedule some time to review this and review all the other elements where you see a change needed and write stories to support this work.

**Comment by blackfalcon** [comment]
@braven112 depending on how this shakes out, this may be a milestone of updates across repos.

**Comment by leeejune** [comment]
Changes to be made:

1. Decrease spacing between left side check and left edge of menu.
2. If possible, add option to have NO checkmark.
3. Darken hover color (change hover state color to bkg-hover-on-light)

All of these changes will be made on the blueprint.

**Comment by blackfalcon** [comment]
Plasse link the updated blueprint to this issue and mention @braven112 so that we can get this prioritized.

**Comment by leeejune** [comment]
https://www.figma.com/file/xwDiIDfSz6j9bM4TD3Ni5N/Menu?node-id=322%3A298

Changes made to spacing and color.

**Comment by braven112** [comment]
@leeejune If you can create issues for any other place you think this is needed we can work on getting those prioritized.

**Comment by leeejune** [comment]
Created #98 for next steps!
