### ISSUE TITLE
Change hover state color and spacing

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-menu#98]
## Is your feature request related to a problem? Please describe.

The contrast between the default background and hover state is too low, making it hard to see. The space between the menu and check box is also too large.

## Describe the solution you'd like

1. Decrease spacing between checkbox and left side of menu
2. Change hover state background color to bkg-hover token

## Additional context

Refer to this blueprint with updated specs: https://www.figma.com/file/xwDiIDfSz6j9bM4TD3Ni5N/Menu?node-id=322%3A298

Development for this updated feature should be merged into the `v3.2-rc` branch, not directly to `main`. 

## Exit criteria 

This issue will be considered complete once the engineered solution is reviewed with @leeejune and is approved.

**Comment by blackfalcon** [comment]
@leeejune this looks great. The only thing I would add is that the `hover`color also be associated with the concept of `activedescendant` as this will be the active state color as the keyboard is moving between menu options while the trigger still maintains `focus`. 

Once you have that, this is 👍 . @braven112 we need a new issue to be written up that is the dev work to meet the new design spec. I would think that @jason-capsule42 would do the work as he is working on the updated a11y model of keyboard interaction.

**Comment by blackfalcon** [comment]
Oh wait... this IS the new dev feature? @leeejune can you make that slight adjustment I spoke to in the previous comment and then we are good to go.

**Comment by leeejune** [comment]
Added a label to associate the `hover` state color to the `activedescendant` concept.

**Comment by blackfalcon** [comment]
@leeejune We no longer have a concept of `divider` being `true` or `false`. This is simply an HTML option using a pre-defined `hr` element. 

Also, please use the concept of `activedescendant` versus simply `active`. There is a difference we need to be specific about. 

<img width="749" alt="Screen Shot 2022-03-09 at 9 18 47 AM" src="https://user-images.githubusercontent.com/181089/157495626-05cd0b47-8468-43e7-b171-28a0bb7966de.png">

**Comment by leeejune** [comment]
@blackfalcon Does that mean that there will be no extra spacing between the menu item and the `hr` element?

**Comment by blackfalcon** [comment]
> @blackfalcon Does that mean that there will be no extra spacing between the menu item and the `hr` element?

The spacing is built into the customized `hr` element. There is no need for an element property to manage this, all a user has to do is insert an `hr` into their HTML when using the element.

**Comment by leeejune** [comment]
@blackfalcon Got it. The divider option will just remain for the designers then! I will leave a note in the blueprint.
